export const RESTART_ON_REMOUNT = '@@saga-injector/restart-on-remount';
export const DAEMON = '@@saga-injector/daemon';
export const ONCE_TILL_UNMOUNT = '@@saga-injector/once-till-unmount';

export const PRIMARY_COLOR = '#fc8182';
export const BOT_MESSAGE_BUBBLE_BACKGROUND_COLOR = '#c83250';
export const BOT_MESSAGE_BUBBLE_FONT_COLOR = 'white';
export const BOT_QUICK_RESPONSE_BACKGROUND_COLOR = '#1E97C7';
export const BOT_QUICK_RESPONSE_FONT_COLOR = 'white';
export const USER_MESSAGE_BUBBLE_BACKGROUND_COLOR = '#555555';
export const USER_MESSAGE_BUBBLE_FONT_COLOR = '#ffffff';
export const BOT_SEND_BUTTON_BACKGROUND_COLOR = BOT_MESSAGE_BUBBLE_BACKGROUND_COLOR;
export const BOT_SEND_BUTTON_ICON_COLOR = BOT_MESSAGE_BUBBLE_FONT_COLOR;
export const USER_SEND_BUTTON_BACKGROUND_COLOR = USER_MESSAGE_BUBBLE_BACKGROUND_COLOR;
export const USER_SEND_BUTTON_ICON_COLOR = USER_MESSAGE_BUBBLE_FONT_COLOR;
