name: Deploy to Digital Ocean

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - run: printf "GTAG_CONTAINER_ID="${{ secrets.GTAG_CONTAINER_ID }}"\n" > .env.webpack
    - run: npm run build
    - uses: master-atul/tar-action@v1.0.2
      with:
        command: c
        files: ./
        outPath: rappo-web-app.tar.gz
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          if pm2 list | grep -q "rappo-web-app"; then
            pm2 delete rappo-web-app
            pm2 save
          fi
    - uses: nogsantos/scp-deploy@master
      with:
        src: ./rappo-web-app.tar.gz
        remote: ~/
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
    - uses: appleboy/ssh-action@master
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        POSTMARK_SERVER_API_TOKEN: ${{ secrets.POSTMARK_SERVER_API_TOKEN }}
        GCLOUD_CREDENTIALS_FILE: ${{ secrets.GCLOUD_CREDENTIALS_FILE }}
        WEBSERVER_HOST: ${{ secrets.WEBSERVER_HOST }}
        SESSION_COOKIE_SECRET: ${{ secrets.SESSION_COOKIE_SECRET }}
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        envs: GOOGLE_APPLICATION_CREDENTIALS,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,POSTMARK_SERVER_API_TOKEN,GCLOUD_CREDENTIALS_FILE,WEBSERVER_HOST,SESSION_COOKIE_SECRET
        script: |
          rm -rf ~/rappo-web-app
          mkdir ~/rappo-web-app
          tar -xf ~/rappo-web-app.tar.gz -C ~/rappo-web-app
          rm -f ~/rappo-web-app.tar.gz
          printf "GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS"\nGOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID"\nGOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET"\nPOSTMARK_SERVER_API_TOKEN="$POSTMARK_SERVER_API_TOKEN"\nWEBSERVER_HOST="$WEBSERVER_HOST"\nSESSION_COOKIE_SECRET="$SESSION_COOKIE_SECRET"\n" > ~/rappo-web-app/.env.server
          echo $GCLOUD_CREDENTIALS_FILE > ~/rappo-web-app/gcloud-credentials.json
          pm2 start npm --cwd ~/rappo-web-app --name rappo-web-app -- run start:prod
          pm2 save
