name: Deploy to Digital Ocean

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run build
    - uses: master-atul/tar-action@v1.0.2
      with:
        command: c
        files: ./
        outPath: rappo-web-app.tar.gz
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          if pm2 list | grep -q "rappo-web-app"; then
            pm2 stop rappo-web-app
          fi
    - uses: nogsantos/scp-deploy@master
      with:
        src: ./rappo-web-app.tar.gz
        remote: ~/
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
    - uses: appleboy/ssh-action@master
      env:
        NODE_ENV: "production"
        ENV_FILE: ${{ secrets.RAPPO_ENV_FILE }}
        GCLOUD_CREDENTIALS_FILE: ${{ secrets.RAPPO_GCLOUD_CREDENTIALS_FILE }}
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        envs: NODE_ENV,ENV_FILE,GCLOUD_CREDENTIALS_FILE
        script: |
          rm -rf ~/rappo-web-app/*
          tar -xf ~/rappo-web-app.tar.gz -C ~/rappo-web-app
          rm -f ~/rappo-web-app.tar.gz
          echo $ENV_FILE > ~/rappo-web-app/.env
          echo $GCLOUD_CREDENTIALS_FILE > ~/rappo-web-app/gcloud-credentials.json
          pm2 start npm --cwd ~/rappo-web-app --name rappo-web-app -- run start:prod
          pm2 save
